# Generated by Django 4.2.4 on 2023-09-24 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_assistant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtubedialogmessage',
            old_name='YouTube_conversation',
            new_name='youtube_conversation',
        ),
    ]
