# Generated by Django 4.2.4 on 2023-09-09 09:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_alter_conversation_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='slug',
        ),
        migrations.AddField(
            model_name='conversation',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
