# Generated by Django 4.2.4 on 2023-09-09 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0004_alter_dialogmessage_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='uuid',
            new_name='uuid_slug',
        ),
    ]
