# Generated by Django 4.2.4 on 2023-09-09 09:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0005_rename_uuid_conversation_uuid_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='uuid_slug',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
