# Generated by Django 4.2.4 on 2023-09-10 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0006_alter_conversation_uuid_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dialogmessage',
            options={'ordering': ['created_at']},
        ),
    ]
