# Generated by Django 4.2.4 on 2023-09-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profileimage_userdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='bio',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
