# Generated by Django 4.2.4 on 2023-09-18 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userdetails_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='profileimage',
            name='user_details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_image', to='users.userdetails'),
        ),
    ]
