# Generated by Django 4.2.4 on 2023-09-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_subscriptionitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionitems',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='stripe_price_id',
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='items',
            field=models.ManyToManyField(to='subscription.subscriptionitems'),
        ),
    ]
