# Generated by Django 4.2.4 on 2023-09-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_remove_subscriptionitems_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionitems',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='subscriptionitems',
            name='name',
            field=models.CharField(default='', max_length=300),
        ),
    ]
