# Generated by Django 4.2.4 on 2023-09-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_subscriptionitems_description_subscriptionitems_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='items',
            field=models.ManyToManyField(blank=True, to='subscription.subscriptionitems'),
        ),
    ]
